name: Larastan

on:
    push:
        paths:
            - '**.php'
            - 'phpstan.neon.dist'

jobs:
    larastan:
        name: larastan
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    coverage: none

            -   name: Install dependencies
                uses: ramsey/composer-install@v2

            -   name: Run Larastan
                run: ./vendor/bin/phpstan --error-format=github
